language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
cache:
  directories:
    - $HOME/.m2/repository

install: |
  set -o errexit -o pipefail
  mvn clean install --activate-profiles dirty,dirty-package --update-snapshots --batch-mode --show-version 2>&1 | tee mvnout.txt
script: |
  set -o errexit -o pipefail
  mvn verify site --define gpg.skip=true --batch-mode --show-version 2>&1 | tee --append mvnout.txt
  
  mvnout=`cat mvnout.txt | grep --perl-regexp "(?i)\\[(ERR|WARN)" | ./target/travis-suppressions-parent.sh`
  if [ -n "${mvnout}" ]; then
    echo ""
    echo "The Maven output contains the following unknown warnings and errors:"
    echo "${mvnout}"
    exit 1
  fi

after_success:
  - rm ./target/site/index.html
  - cp ./CHANGELOG.md ./target/site/CHANGELOG.md
  - cp ./README.md ./target/site/README.md
  
  # Modules
  - cp -R ./parent/target/site ./target/site/parent
  - cp -R ./parent-archetype/target/site ./target/site/parent-archetype
  - cp -R ./utils/target/site ./target/site/utils
  - cp -R ./utils-annotations/target/site ./target/site/utils-annotations
  - cp -R ./utils-test/target/site ./target/site/utils-test
deploy:
  provider: pages
  local_dir: ./target/site
  edge: true
  on:
    branch: master
    jdk: openjdk8
